-- chunkname: @scripts/settings/payload_speed_settings.lua

PayloadSpeedSettings = not not PayloadSpeedSettings
PayloadSpeedSettings.flat = not not PayloadSpeedSettings.flat
PayloadSpeedSettings.flat.pushed = not not PayloadSpeedSettings.flat.pushed
PayloadSpeedSettings.flat.pushed.speed = 0.8
PayloadSpeedSettings.flat.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.flat.pushed.acceleration = 0.5
PayloadSpeedSettings.flat.not_pushed = not not PayloadSpeedSettings.flat.not_pushed
PayloadSpeedSettings.flat.not_pushed.speed = 0
PayloadSpeedSettings.flat.not_pushed.acceleration = 0.5
PayloadSpeedSettings.uphill = not not PayloadSpeedSettings.uphill
PayloadSpeedSettings.uphill.pushed = not not PayloadSpeedSettings.uphill.pushed
PayloadSpeedSettings.uphill.pushed.speed = 0.4
PayloadSpeedSettings.uphill.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.uphill.pushed.acceleration = 1.2
PayloadSpeedSettings.uphill.not_pushed = not not PayloadSpeedSettings.uphill.not_pushed
PayloadSpeedSettings.uphill.not_pushed.speed = -1
PayloadSpeedSettings.uphill.not_pushed.acceleration = 0.3
PayloadSpeedSettings.downhill = not not PayloadSpeedSettings.downhill
PayloadSpeedSettings.downhill.pushed = not not PayloadSpeedSettings.downhill.pushed
PayloadSpeedSettings.downhill.pushed.speed = 1.6
PayloadSpeedSettings.downhill.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.downhill.pushed.acceleration = 0.5
PayloadSpeedSettings.downhill.not_pushed = not not PayloadSpeedSettings.downhill.not_pushed
PayloadSpeedSettings.downhill.not_pushed.speed = 1.2
PayloadSpeedSettings.downhill.not_pushed.acceleration = 0.2
PayloadSpeedSettings.muddy = not not PayloadSpeedSettings.muddy
PayloadSpeedSettings.muddy.pushed = not not PayloadSpeedSettings.muddy.pushed
PayloadSpeedSettings.muddy.pushed.speed = 0.7
PayloadSpeedSettings.muddy.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.muddy.pushed.acceleration = 0.5
PayloadSpeedSettings.muddy.not_pushed = not not PayloadSpeedSettings.muddy.not_pushed
PayloadSpeedSettings.muddy.not_pushed.speed = 0
PayloadSpeedSettings.muddy.not_pushed.acceleration = 0.5
PayloadSpeedSettings.small_flat = not not PayloadSpeedSettings.small_flat
PayloadSpeedSettings.small_flat.pushed = not not PayloadSpeedSettings.small_flat.pushed
PayloadSpeedSettings.small_flat.pushed.speed = 1.4
PayloadSpeedSettings.small_flat.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.small_flat.pushed.acceleration = 0.5
PayloadSpeedSettings.small_flat.not_pushed = not not PayloadSpeedSettings.small_flat.not_pushed
PayloadSpeedSettings.small_flat.not_pushed.speed = 0
PayloadSpeedSettings.small_flat.not_pushed.acceleration = 0.5
PayloadSpeedSettings.small_slowdown = not not PayloadSpeedSettings.small_slowdown
PayloadSpeedSettings.small_slowdown.pushed = not not PayloadSpeedSettings.small_slowdown.pushed
PayloadSpeedSettings.small_slowdown.pushed.speed = 0
PayloadSpeedSettings.small_slowdown.pushed.bonus_speed_per_player = 0
PayloadSpeedSettings.small_slowdown.pushed.acceleration = 0.5
PayloadSpeedSettings.small_slowdown.not_pushed = not not PayloadSpeedSettings.small_slowdown.not_pushed
PayloadSpeedSettings.small_slowdown.not_pushed.speed = 0
PayloadSpeedSettings.small_slowdown.not_pushed.acceleration = 0.5
PayloadSpeedSettings.small_uphill = not not PayloadSpeedSettings.small_uphill
PayloadSpeedSettings.small_uphill.pushed = not not PayloadSpeedSettings.small_uphill.pushed
PayloadSpeedSettings.small_uphill.pushed.speed = 1.3
PayloadSpeedSettings.small_uphill.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.small_uphill.pushed.acceleration = 1.2
PayloadSpeedSettings.small_uphill.not_pushed = not not PayloadSpeedSettings.small_uphill.not_pushed
PayloadSpeedSettings.small_uphill.not_pushed.speed = -2.5
PayloadSpeedSettings.small_uphill.not_pushed.acceleration = 0.75
PayloadSpeedSettings.small_downhill_slow = not not PayloadSpeedSettings.small_downhill_slow
PayloadSpeedSettings.small_downhill_slow.pushed = not not PayloadSpeedSettings.small_downhill_slow.pushed
PayloadSpeedSettings.small_downhill_slow.pushed.speed = 2
PayloadSpeedSettings.small_downhill_slow.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.small_downhill_slow.pushed.acceleration = 0.5
PayloadSpeedSettings.small_downhill_slow.not_pushed = not not PayloadSpeedSettings.small_downhill_slow.not_pushed
PayloadSpeedSettings.small_downhill_slow.not_pushed.speed = 1
PayloadSpeedSettings.small_downhill_slow.not_pushed.acceleration = 0.2
PayloadSpeedSettings.small_downhill = not not PayloadSpeedSettings.small_downhill
PayloadSpeedSettings.small_downhill.pushed = not not PayloadSpeedSettings.small_downhill.pushed
PayloadSpeedSettings.small_downhill.pushed.speed = 2.5
PayloadSpeedSettings.small_downhill.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.small_downhill.pushed.acceleration = 0.5
PayloadSpeedSettings.small_downhill.not_pushed = not not PayloadSpeedSettings.small_downhill.not_pushed
PayloadSpeedSettings.small_downhill.not_pushed.speed = 2
PayloadSpeedSettings.small_downhill.not_pushed.acceleration = 0.2
PayloadSpeedSettings.small_downhill_fast = not not PayloadSpeedSettings.small_downhill_fast
PayloadSpeedSettings.small_downhill_fast.pushed = not not PayloadSpeedSettings.small_downhill_fast.pushed
PayloadSpeedSettings.small_downhill_fast.pushed.speed = 3.5
PayloadSpeedSettings.small_downhill_fast.pushed.bonus_speed_per_player = 0.05
PayloadSpeedSettings.small_downhill_fast.pushed.acceleration = 0.5
PayloadSpeedSettings.small_downhill_fast.not_pushed = not not PayloadSpeedSettings.small_downhill_fast.not_pushed
PayloadSpeedSettings.small_downhill_fast.not_pushed.speed = 3
PayloadSpeedSettings.small_downhill_fast.not_pushed.acceleration = 0.2
PayloadSpeedSettings.small_downhill_chase_01 = not not PayloadSpeedSettings.small_downhill_chase_01
PayloadSpeedSettings.small_downhill_chase_01.pushed = not not PayloadSpeedSettings.small_downhill_chase_01.pushed
PayloadSpeedSettings.small_downhill_chase_01.pushed.speed = 7.5
PayloadSpeedSettings.small_downhill_chase_01.pushed.bonus_speed_per_player = 0
PayloadSpeedSettings.small_downhill_chase_01.pushed.acceleration = 4
PayloadSpeedSettings.small_downhill_chase_01.not_pushed = not not PayloadSpeedSettings.small_downhill_chase_01.not_pushed
PayloadSpeedSettings.small_downhill_chase_01.not_pushed.speed = 7.5
PayloadSpeedSettings.small_downhill_chase_01.not_pushed.acceleration = 4
PayloadSpeedSettings.small_downhill_chase_02 = not not PayloadSpeedSettings.small_downhill_chase_02
PayloadSpeedSettings.small_downhill_chase_02.pushed = not not PayloadSpeedSettings.small_downhill_chase_02.pushed
PayloadSpeedSettings.small_downhill_chase_02.pushed.speed = 6.5
PayloadSpeedSettings.small_downhill_chase_02.pushed.bonus_speed_per_player = 0
PayloadSpeedSettings.small_downhill_chase_02.pushed.acceleration = 3
PayloadSpeedSettings.small_downhill_chase_02.not_pushed = not not PayloadSpeedSettings.small_downhill_chase_02.not_pushed
PayloadSpeedSettings.small_downhill_chase_02.not_pushed.speed = 6.5
PayloadSpeedSettings.small_downhill_chase_02.not_pushed.acceleration = 3
PayloadSpeedSettings.ussingen_downhill_mansion_01 = not not PayloadSpeedSettings.ussingen_downhill_mansion_01
PayloadSpeedSettings.ussingen_downhill_mansion_01.pushed = not not PayloadSpeedSettings.ussingen_downhill_mansion_01.pushed
PayloadSpeedSettings.ussingen_downhill_mansion_01.pushed.speed = 6.5
PayloadSpeedSettings.ussingen_downhill_mansion_01.pushed.bonus_speed_per_player = 0
PayloadSpeedSettings.ussingen_downhill_mansion_01.pushed.acceleration = 3
PayloadSpeedSettings.ussingen_downhill_mansion_01.not_pushed = not not PayloadSpeedSettings.ussingen_downhill_mansion_01.not_pushed
PayloadSpeedSettings.ussingen_downhill_mansion_01.not_pushed.speed = 6.5
PayloadSpeedSettings.ussingen_downhill_mansion_01.not_pushed.acceleration = 3
PayloadSpeedSettings.farmlands_heavy_load_01 = not not PayloadSpeedSettings.farmlands_heavy_load_01
PayloadSpeedSettings.farmlands_heavy_load_01.pushed = not not PayloadSpeedSettings.farmlands_heavy_load_01.pushed
PayloadSpeedSettings.farmlands_heavy_load_01.pushed.speed = 0.2
PayloadSpeedSettings.farmlands_heavy_load_01.pushed.bonus_speed_per_player = 0.07
PayloadSpeedSettings.farmlands_heavy_load_01.pushed.acceleration = 1
PayloadSpeedSettings.farmlands_heavy_load_01.not_pushed = not not PayloadSpeedSettings.farmlands_heavy_load_01.not_pushed
PayloadSpeedSettings.farmlands_heavy_load_01.not_pushed.speed = 0
PayloadSpeedSettings.farmlands_heavy_load_01.not_pushed.acceleration = 0.2
PayloadSpeedSettings.normal = not not PayloadSpeedSettings.normal
PayloadSpeedSettings.normal.pushed = not not PayloadSpeedSettings.normal.pushed
PayloadSpeedSettings.normal.pushed.speed = 2.5
PayloadSpeedSettings.normal.pushed.bonus_speed_per_player = 0.25
PayloadSpeedSettings.normal.pushed.acceleration = 0.25
PayloadSpeedSettings.normal.not_pushed = not not PayloadSpeedSettings.normal.not_pushed
PayloadSpeedSettings.normal.not_pushed.speed = 0
PayloadSpeedSettings.normal.not_pushed.acceleration = 0.25
PayloadSpeedSettings.sled_ice = not not PayloadSpeedSettings.sled_ice
PayloadSpeedSettings.sled_ice.pushed = not not PayloadSpeedSettings.sled_ice.pushed
PayloadSpeedSettings.sled_ice.pushed.speed = 3
PayloadSpeedSettings.sled_ice.pushed.bonus_speed_per_player = 0.25
PayloadSpeedSettings.sled_ice.pushed.acceleration = 1
PayloadSpeedSettings.sled_ice.not_pushed = not not PayloadSpeedSettings.sled_ice.not_pushed
PayloadSpeedSettings.sled_ice.not_pushed.speed = 0
PayloadSpeedSettings.sled_ice.not_pushed.acceleration = 0.5
PayloadSpeedSettings.sled_normal = not not PayloadSpeedSettings.sled_normal
PayloadSpeedSettings.sled_normal.pushed = not not PayloadSpeedSettings.sled_normal.pushed
PayloadSpeedSettings.sled_normal.pushed.speed = 1.85
PayloadSpeedSettings.sled_normal.pushed.bonus_speed_per_player = 0.75
PayloadSpeedSettings.sled_normal.pushed.acceleration = 1.75
PayloadSpeedSettings.sled_normal.not_pushed = not not PayloadSpeedSettings.sled_normal.not_pushed
PayloadSpeedSettings.sled_normal.not_pushed.speed = 0
PayloadSpeedSettings.sled_normal.not_pushed.acceleration = 1.75
PayloadSpeedSettings.sled_fast = not not PayloadSpeedSettings.sled_fast
PayloadSpeedSettings.sled_fast.pushed = not not PayloadSpeedSettings.sled_fast.pushed
PayloadSpeedSettings.sled_fast.pushed.speed = 8
PayloadSpeedSettings.sled_fast.pushed.bonus_speed_per_player = 0
PayloadSpeedSettings.sled_fast.pushed.acceleration = 3
PayloadSpeedSettings.sled_fast.not_pushed = not not PayloadSpeedSettings.sled_fast.not_pushed
PayloadSpeedSettings.sled_fast.not_pushed.speed = 8
PayloadSpeedSettings.sled_fast.not_pushed.acceleration = 2
PayloadSpeedSettings.sled_downhill = not not PayloadSpeedSettings.sled_downhill
PayloadSpeedSettings.sled_downhill.pushed = not not PayloadSpeedSettings.small_downhill.pushed
PayloadSpeedSettings.sled_downhill.pushed.speed = 5.5
PayloadSpeedSettings.sled_downhill.pushed.bonus_speed_per_player = 0.5
PayloadSpeedSettings.sled_downhill.pushed.acceleration = 2.5
PayloadSpeedSettings.sled_downhill.not_pushed = not not PayloadSpeedSettings.sled_downhill.not_pushed
PayloadSpeedSettings.sled_downhill.not_pushed.speed = 5
PayloadSpeedSettings.sled_downhill.not_pushed.acceleration = 1.75
PayloadSpeedSettings.sled_fast02 = not not PayloadSpeedSettings.sled_fast02
PayloadSpeedSettings.sled_fast02.pushed = not not PayloadSpeedSettings.sled_fast02.pushed
PayloadSpeedSettings.sled_fast02.pushed.speed = 9
PayloadSpeedSettings.sled_fast02.pushed.bonus_speed_per_player = 0
PayloadSpeedSettings.sled_fast02.pushed.acceleration = 4
PayloadSpeedSettings.sled_fast02.not_pushed = not not PayloadSpeedSettings.sled_fast02.not_pushed
PayloadSpeedSettings.sled_fast02.not_pushed.speed = 9
PayloadSpeedSettings.sled_fast02.not_pushed.acceleration = 4
PayloadSpeedSettings.tiny_uphill = not not PayloadSpeedSettings.tiny_uphill
PayloadSpeedSettings.tiny_uphill.pushed = not not PayloadSpeedSettings.tiny_uphill.pushed
PayloadSpeedSettings.tiny_uphill.pushed.speed = 1.45
PayloadSpeedSettings.tiny_uphill.pushed.bonus_speed_per_player = 0.25
PayloadSpeedSettings.tiny_uphill.pushed.acceleration = 0.75
PayloadSpeedSettings.tiny_uphill.not_pushed = not not PayloadSpeedSettings.tiny_uphill.not_pushed
PayloadSpeedSettings.tiny_uphill.not_pushed.speed = -1.75
PayloadSpeedSettings.tiny_uphill.not_pushed.acceleration = 1.2
