-- chunkname: @scripts/imgui/imgui_generate_weapon_poses.lua

ImguiGenerateWeaponPoses = class(ImguiGenerateWeaponPoses)

local num = 6

ImguiGenerateWeaponPoses.init = function (self)
	-- function 1
	self._num_weapon_poses = num
	self._alpha_timer = 0
end

ImguiGenerateWeaponPoses.update = function (arg_2_0)
	-- function 2
	return
end

ImguiGenerateWeaponPoses.is_persistent = function (arg_3_0)
	-- function 3
	return false
end

ImguiGenerateWeaponPoses._generate_weapon_poses = function (self)
	-- function 4
	local var_4_0 = FileSystem(script_data.source_dir)

	if not var_4_0 then
		return
	end

	local str = "scripts//settings//equipment//item_master_list_weapon_poses.lua"

	if not FileSystem.exists(var_4_0, str) then
		FileSystem.remove_file(var_4_0, str)
	end

	FileSystem.make_file(var_4_0, str)

	local open_output = FileSystem.open_output(var_4_0, str)

	self:_add_header(open_output)
	self:_add_default_pose(open_output)

	for k, v in pairs(ItemMasterList) do
		local slot_type = v.slot_type

		if slot_type == "melee" or slot_type == "ranged" or not v.skin_combination_table then
			if not string.find(v.name, "^vs_") then
				print(v.name)
				self:_add_weapon_poses(open_output, v)
			else
				print("skipping:", v.name)
			end
		end
	end

	OutputArchive.close(open_output)
end

ImguiGenerateWeaponPoses._add_header = function (self, arg_5_1)
	-- function 5
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- ****                                                     ****\n")
	OutputArchive.write(arg_5_1, "-- ****   This File is AUTOGENERATED using the Imgui Tool   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   GenerateWeaponPoses. To use the tool press 'F3'   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   to open the Imgui Menu Bar and find the tool in   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   'tools/Generate Weapon Poses'. To update weapon   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   poses just press generate. This will regenerate   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   this file with all base weapons currently         ****\n")
	OutputArchive.write(arg_5_1, "-- ****   available in the game. Make sure to not include   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   any weapons that shouldn't be part of the         ****\n")
	OutputArchive.write(arg_5_1, "-- ****   current release to avoid leaks.                   ****\n")
	OutputArchive.write(arg_5_1, "-- ****                                                     ****\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- ****                                                     ****\n")
	OutputArchive.write(arg_5_1, "-- ****          NUM WEAPON POSES PER WEAPON: " .. tostring(self._num_weapon_poses) .. "             ****\n")
	OutputArchive.write(arg_5_1, "-- ****                                                     ****\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "\n")
end

ImguiGenerateWeaponPoses._add_default_pose = function (arg_6_0, arg_6_1)
	-- function 6
	OutputArchive.write(arg_6_1, "ItemMasterList.default_weapon_pose_01 = {\n")
	OutputArchive.write(arg_6_1, "\tname = \"default_weapon_pose_01\",\n")
	OutputArchive.write(arg_6_1, "\tdisplay_name = \"default_weapon_pose_01\",\n")
	OutputArchive.write(arg_6_1, "\tdescription = \"default_weapon_pose_01_desc\",\n")
	OutputArchive.write(arg_6_1, "\tslot_type = \"weapon_pose\",\n")
	OutputArchive.write(arg_6_1, "\titem_type = \"weapon_pose\",\n")
	OutputArchive.write(arg_6_1, "\tinformation_text = \"information_weapon_pose\",\n")
	OutputArchive.write(arg_6_1, "\tdata = {},\n")
	OutputArchive.write(arg_6_1, "\thud_icon = \"empty\",\n")
	OutputArchive.write(arg_6_1, "\trarity = \"plentiful\",\n")
	OutputArchive.write(arg_6_1, "\tpose_index = 1,\n")
	OutputArchive.write(arg_6_1, "\tparent = \"default\",\n")
	OutputArchive.write(arg_6_1, "\ttemplate = \"pose_template\",\n")
	OutputArchive.write(arg_6_1, "\tcan_wield = CanWieldAllItemTemplates,\n")
	OutputArchive.write(arg_6_1, "}\n\n")
end

ImguiGenerateWeaponPoses._add_weapon_poses = function (self, arg_7_1, arg_7_2)
	-- function 7
	local name = arg_7_2.name
	local str = "{ "

	for k, v in pairs(arg_7_2.can_wield) do
		str = str .. "\"" .. v .. "\","
	end

	local str_2 = str .. " }"

	for k_2 = 1, self._num_weapon_poses do
		local format = string.format("%02d", k_2)

		OutputArchive.write(arg_7_1, "ItemMasterList." .. name .. "_weapon_pose_" .. format .. " = {\n")
		OutputArchive.write(arg_7_1, "\tname = \"" .. string.format(Localize(name .. "_emote_wheel"), format) .. "\",\n")
		OutputArchive.write(arg_7_1, "\tdisplay_name = \"" .. name .. "_emote_wheel" .. "\",\n")
		OutputArchive.write(arg_7_1, "\tdescription = \"weapon_pose_emote_description\",\n")
		OutputArchive.write(arg_7_1, "\tslot_type = \"weapon_pose\",\n")
		OutputArchive.write(arg_7_1, "\titem_type = \"weapon_pose\",\n")
		OutputArchive.write(arg_7_1, "\tinformation_text = \"information_weapon_pose\",\n")
		OutputArchive.write(arg_7_1, "\tdata = { anim_event = \"anim_pose_" .. format .. "\", hide_weapons = false },\n")
		OutputArchive.write(arg_7_1, "\thud_icon = \"" .. name .. string.format("_%02d", k_2) .. "\",\n")
		OutputArchive.write(arg_7_1, "\tinventory_icon = \"" .. name .. string.format("_%02d", k_2) .. "\",\n")
		OutputArchive.write(arg_7_1, "\trarity = \"exotic\",\n")
		OutputArchive.write(arg_7_1, "\tpose_index = " .. k_2 .. ",\n")
		OutputArchive.write(arg_7_1, "\tparent = \"" .. name .. "\",\n")
		OutputArchive.write(arg_7_1, "\ttemplate = \"pose_template\",\n")
		OutputArchive.write(arg_7_1, "\tcan_wield = " .. str_2 .. ",\n")
		OutputArchive.write(arg_7_1, "}\n\n")
	end
end

ImguiGenerateWeaponPoses.draw = function (self)
	-- function 8
	local begin_window = Imgui.begin_window("Generate Item Master List for Weapon Poses")

	Imgui.set_window_size(340, 120)
	Imgui.text("Number of weapon poses per weapon")

	local input_text, var_8_2 = Imgui.input_text("", self._num_weapon_poses)

	if not var_8_2 then
		self._num_weapon_poses = input_text
	end

	if not Imgui.button("Generate") then
		self:_generate_weapon_poses()

		self._generated = true
		self._current_color = {
			math.random(255),
			math.random(255),
			math.random(255)
		}
		self._generated_with_num_weapon_poses = self._num_weapon_poses
		self._alpha_timer = Application.time_since_launch() + 2
	end

	if not self._generated then
		local time_since_launch = Application.time_since_launch()
		local num = 255
		local num_2 = 0.5

		if time_since_launch > self._alpha_timer then
			num = 0
		elseif num_2 > self._alpha_timer - time_since_launch then
			num = (self._alpha_timer - time_since_launch) / 0.5 * 255
		end

		Imgui.same_line(10)
		Imgui.text_colored("Done!", self._current_color[1], self._current_color[2], self._current_color[3], num)
		Imgui.indent(74)
		Imgui.text_colored(string.format("Using %q poses per base weapon", self._generated_with_num_weapon_poses), self._current_color[1], self._current_color[2], self._current_color[3], num)
	end

	Imgui.end_window()

	return begin_window
end
