-- chunkname: @scripts/imgui/imgui_generate_weapon_poses.lua

ImguiGenerateWeaponPoses = class(ImguiGenerateWeaponPoses)

local var_0_0 = 6

ImguiGenerateWeaponPoses.init = function (arg_1_0)
	arg_1_0._num_weapon_poses = var_0_0
	arg_1_0._alpha_timer = 0
end

ImguiGenerateWeaponPoses.update = function (arg_2_0)
	return
end

ImguiGenerateWeaponPoses.is_persistent = function (arg_3_0)
	return false
end

ImguiGenerateWeaponPoses._generate_weapon_poses = function (arg_4_0)
	local var_4_0 = FileSystem(script_data.source_dir)

	if not var_4_0 then
		return
	end

	local var_4_1 = "scripts//settings//equipment//item_master_list_weapon_poses.lua"

	if FileSystem.exists(var_4_0, var_4_1) then
		FileSystem.remove_file(var_4_0, var_4_1)
	end

	FileSystem.make_file(var_4_0, var_4_1)

	local var_4_2 = FileSystem.open_output(var_4_0, var_4_1)

	arg_4_0:_add_header(var_4_2)
	arg_4_0:_add_default_pose(var_4_2)

	for iter_4_0, iter_4_1 in pairs(ItemMasterList) do
		local var_4_3 = iter_4_1.slot_type

		if (var_4_3 == "melee" or var_4_3 == "ranged") and iter_4_1.skin_combination_table then
			if not string.find(iter_4_1.name, "^vs_") then
				print(iter_4_1.name)
				arg_4_0:_add_weapon_poses(var_4_2, iter_4_1)
			else
				print("skipping:", iter_4_1.name)
			end
		end
	end

	OutputArchive.close(var_4_2)
end

ImguiGenerateWeaponPoses._add_header = function (arg_5_0, arg_5_1)
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- ****                                                     ****\n")
	OutputArchive.write(arg_5_1, "-- ****   This File is AUTOGENERATED using the Imgui Tool   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   GenerateWeaponPoses. To use the tool press 'F3'   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   to open the Imgui Menu Bar and find the tool in   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   'tools/Generate Weapon Poses'. To update weapon   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   poses just press generate. This will regenerate   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   this file with all base weapons currently         ****\n")
	OutputArchive.write(arg_5_1, "-- ****   available in the game. Make sure to not include   ****\n")
	OutputArchive.write(arg_5_1, "-- ****   any weapons that shouldn't be part of the         ****\n")
	OutputArchive.write(arg_5_1, "-- ****   current release to avoid leaks.                   ****\n")
	OutputArchive.write(arg_5_1, "-- ****                                                     ****\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- ****                                                     ****\n")
	OutputArchive.write(arg_5_1, "-- ****          NUM WEAPON POSES PER WEAPON: " .. tostring(arg_5_0._num_weapon_poses) .. "             ****\n")
	OutputArchive.write(arg_5_1, "-- ****                                                     ****\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "-- *************************************************************\n")
	OutputArchive.write(arg_5_1, "\n")
end

ImguiGenerateWeaponPoses._add_default_pose = function (arg_6_0, arg_6_1)
	OutputArchive.write(arg_6_1, "ItemMasterList.default_weapon_pose_01 = {\n")
	OutputArchive.write(arg_6_1, "\tname = \"default_weapon_pose_01\",\n")
	OutputArchive.write(arg_6_1, "\tdisplay_name = \"default_weapon_pose_01\",\n")
	OutputArchive.write(arg_6_1, "\tdescription = \"default_weapon_pose_01_desc\",\n")
	OutputArchive.write(arg_6_1, "\tslot_type = \"weapon_pose\",\n")
	OutputArchive.write(arg_6_1, "\titem_type = \"weapon_pose\",\n")
	OutputArchive.write(arg_6_1, "\tinformation_text = \"information_weapon_pose\",\n")
	OutputArchive.write(arg_6_1, "\tdata = {},\n")
	OutputArchive.write(arg_6_1, "\thud_icon = \"empty\",\n")
	OutputArchive.write(arg_6_1, "\trarity = \"plentiful\",\n")
	OutputArchive.write(arg_6_1, "\tpose_index = 1,\n")
	OutputArchive.write(arg_6_1, "\tparent = \"default\",\n")
	OutputArchive.write(arg_6_1, "\ttemplate = \"pose_template\",\n")
	OutputArchive.write(arg_6_1, "\tcan_wield = CanWieldAllItemTemplates,\n")
	OutputArchive.write(arg_6_1, "}\n\n")
end

ImguiGenerateWeaponPoses._add_weapon_poses = function (arg_7_0, arg_7_1, arg_7_2)
	local var_7_0 = arg_7_2.name
	local var_7_1 = "{ "

	for iter_7_0, iter_7_1 in pairs(arg_7_2.can_wield) do
		var_7_1 = var_7_1 .. "\"" .. iter_7_1 .. "\","
	end

	local var_7_2 = var_7_1 .. " }"

	for iter_7_2 = 1, arg_7_0._num_weapon_poses do
		local var_7_3 = string.format("%02d", iter_7_2)

		OutputArchive.write(arg_7_1, "ItemMasterList." .. var_7_0 .. "_weapon_pose_" .. var_7_3 .. " = {\n")
		OutputArchive.write(arg_7_1, "\tname = \"" .. string.format(Localize(var_7_0 .. "_emote_wheel"), var_7_3) .. "\",\n")
		OutputArchive.write(arg_7_1, "\tdisplay_name = \"" .. var_7_0 .. "_emote_wheel" .. "\",\n")
		OutputArchive.write(arg_7_1, "\tdescription = \"weapon_pose_emote_description\",\n")
		OutputArchive.write(arg_7_1, "\tslot_type = \"weapon_pose\",\n")
		OutputArchive.write(arg_7_1, "\titem_type = \"weapon_pose\",\n")
		OutputArchive.write(arg_7_1, "\tinformation_text = \"information_weapon_pose\",\n")
		OutputArchive.write(arg_7_1, "\tdata = { anim_event = \"anim_pose_" .. var_7_3 .. "\", hide_weapons = false },\n")
		OutputArchive.write(arg_7_1, "\thud_icon = \"" .. var_7_0 .. string.format("_%02d", iter_7_2) .. "\",\n")
		OutputArchive.write(arg_7_1, "\tinventory_icon = \"" .. var_7_0 .. string.format("_%02d", iter_7_2) .. "\",\n")
		OutputArchive.write(arg_7_1, "\trarity = \"exotic\",\n")
		OutputArchive.write(arg_7_1, "\tpose_index = " .. iter_7_2 .. ",\n")
		OutputArchive.write(arg_7_1, "\tparent = \"" .. var_7_0 .. "\",\n")
		OutputArchive.write(arg_7_1, "\ttemplate = \"pose_template\",\n")
		OutputArchive.write(arg_7_1, "\tcan_wield = " .. var_7_2 .. ",\n")
		OutputArchive.write(arg_7_1, "}\n\n")
	end
end

ImguiGenerateWeaponPoses.draw = function (arg_8_0)
	local var_8_0 = Imgui.begin_window("Generate Item Master List for Weapon Poses")

	Imgui.set_window_size(340, 120)
	Imgui.text("Number of weapon poses per weapon")

	local var_8_1, var_8_2 = Imgui.input_text("", arg_8_0._num_weapon_poses)

	if var_8_2 then
		arg_8_0._num_weapon_poses = var_8_1
	end

	if Imgui.button("Generate") then
		arg_8_0:_generate_weapon_poses()

		arg_8_0._generated = true
		arg_8_0._current_color = {
			math.random(255),
			math.random(255),
			math.random(255)
		}
		arg_8_0._generated_with_num_weapon_poses = arg_8_0._num_weapon_poses
		arg_8_0._alpha_timer = Application.time_since_launch() + 2
	end

	if arg_8_0._generated then
		local var_8_3 = Application.time_since_launch()
		local var_8_4 = 255
		local var_8_5 = 0.5

		if var_8_3 > arg_8_0._alpha_timer then
			var_8_4 = 0
		elseif var_8_5 > arg_8_0._alpha_timer - var_8_3 then
			var_8_4 = (arg_8_0._alpha_timer - var_8_3) / 0.5 * 255
		end

		Imgui.same_line(10)
		Imgui.text_colored("Done!", arg_8_0._current_color[1], arg_8_0._current_color[2], arg_8_0._current_color[3], var_8_4)
		Imgui.indent(74)
		Imgui.text_colored(string.format("Using %q poses per base weapon", arg_8_0._generated_with_num_weapon_poses), arg_8_0._current_color[1], arg_8_0._current_color[2], arg_8_0._current_color[3], var_8_4)
	end

	Imgui.end_window()

	return var_8_0
end
