-- chunkname: @scripts/settings/dlcs/morris/deus_map_baked_base_graphs.lua

local scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_ruin = require("scripts/settings/dlcs/morris/deus_map_baked_base_graphs_journey_ruin")
local scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_cave = require("scripts/settings/dlcs/morris/deus_map_baked_base_graphs_journey_cave")
local scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_ice = require("scripts/settings/dlcs/morris/deus_map_baked_base_graphs_journey_ice")
local scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_citadel = require("scripts/settings/dlcs/morris/deus_map_baked_base_graphs_journey_citadel")

return {
	default = scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_ruin,
	journey_ruin = scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_ruin,
	journey_cave = scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_cave,
	journey_ice = scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_ice,
	journey_citadel = scripts_settings_dlcs_morris_deus_map_baked_base_graphs_journey_citadel
}
