-- chunkname: @scripts/settings/equipment/weapon_properties_morris.lua

local var_0_0 = {}
local var_0_1 = {
	stockpile = {
		variable_multiplier = {
			0.2,
			0.4
		}
	},
	deus_coins_greed = {
		variable_multiplier = {
			0.1,
			0.3
		}
	},
	deus_power_vs_chaos = {
		variable_multiplier = {
			0.05,
			0.1
		}
	}
}

var_0_0.buff_templates = {
	stockpile = {
		buffs = {
			{
				update_func = "update_stockpile_buff",
				name = "stockpile",
				stat_buff = "total_ammo",
				delay = 0,
				remove_buff_func = "remove_stockpile_buff"
			}
		}
	},
	deus_coins_greed = {
		buffs = {
			{
				stat_buff = "deus_coins_greed",
				name = "deus_coins_greed"
			}
		}
	},
	properties_deus_power_vs_chaos = {
		buffs = {
			{
				stat_buff = "power_level_chaos"
			}
		}
	}
}
var_0_0.properties = {
	stockpile = {
		display_name = "properties_stockpile",
		advanced_description = "description_properties_stockpile",
		icon = "bardin_ironbreaker_gromril_armour",
		buff_name = "stockpile",
		description_values = {
			{
				value_type = "percent",
				value = var_0_1.stockpile.variable_multiplier
			}
		}
	},
	deus_coins_greed = {
		display_name = "properties_deus_coins_greed",
		advanced_description = "description_properties_deus_coins_greed",
		icon = "bardin_ironbreaker_gromril_armour",
		no_wield_required = true,
		buff_name = "deus_coins_greed",
		description_values = {
			{
				value_type = "percent",
				value = var_0_1.deus_coins_greed.variable_multiplier
			}
		}
	},
	deus_power_vs_chaos = {
		display_name = "properties_power_vs_chaos",
		buffer = "server",
		advanced_description = "description_properties_power_vs_chaos",
		buff_name = "properties_deus_power_vs_chaos",
		description_values = {
			{
				value_type = "percent",
				value = var_0_1.deus_power_vs_chaos.variable_multiplier
			}
		}
	}
}

for iter_0_0, iter_0_1 in pairs(var_0_0.properties) do
	iter_0_1.name = iter_0_0
end

var_0_0.combinations = {
	deus_melee = {
		common = {
			{
				"crit_chance"
			},
			{
				"crit_boost"
			},
			{
				"stamina"
			},
			{
				"attack_speed"
			},
			{
				"stamina"
			},
			{
				"block_cost"
			},
			{
				"power_vs_skaven"
			},
			{
				"power_vs_chaos"
			},
			{
				"deus_coins_greed"
			}
		},
		rare = {
			{
				"crit_boost",
				"push_block_arc"
			},
			{
				"crit_chance",
				"push_block_arc"
			},
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"attack_speed",
				"push_block_arc"
			},
			{
				"attack_speed",
				"crit_boost"
			},
			{
				"attack_speed",
				"crit_chance"
			},
			{
				"stamina",
				"push_block_arc"
			},
			{
				"stamina",
				"crit_boost"
			},
			{
				"stamina",
				"crit_chance"
			},
			{
				"stamina",
				"attack_speed"
			},
			{
				"block_cost",
				"push_block_arc"
			},
			{
				"block_cost",
				"crit_boost"
			},
			{
				"block_cost",
				"crit_chance"
			},
			{
				"block_cost",
				"attack_speed"
			},
			{
				"block_cost",
				"stamina"
			},
			{
				"power_vs_skaven",
				"push_block_arc"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"attack_speed"
			},
			{
				"power_vs_skaven",
				"stamina"
			},
			{
				"power_vs_skaven",
				"block_cost"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			},
			{
				"power_vs_chaos",
				"push_block_arc"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"attack_speed"
			},
			{
				"power_vs_chaos",
				"stamina"
			},
			{
				"power_vs_chaos",
				"block_cost"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"push_block_arc"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"attack_speed"
			},
			{
				"deus_coins_greed",
				"stamina"
			},
			{
				"deus_coins_greed",
				"block_cost"
			}
		},
		exotic = {
			{
				"crit_boost",
				"push_block_arc"
			},
			{
				"crit_chance",
				"push_block_arc"
			},
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"attack_speed",
				"push_block_arc"
			},
			{
				"attack_speed",
				"crit_boost"
			},
			{
				"attack_speed",
				"crit_chance"
			},
			{
				"stamina",
				"push_block_arc"
			},
			{
				"stamina",
				"crit_boost"
			},
			{
				"stamina",
				"crit_chance"
			},
			{
				"stamina",
				"attack_speed"
			},
			{
				"block_cost",
				"push_block_arc"
			},
			{
				"block_cost",
				"crit_boost"
			},
			{
				"block_cost",
				"crit_chance"
			},
			{
				"block_cost",
				"attack_speed"
			},
			{
				"block_cost",
				"stamina"
			},
			{
				"power_vs_skaven",
				"push_block_arc"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"attack_speed"
			},
			{
				"power_vs_skaven",
				"stamina"
			},
			{
				"power_vs_skaven",
				"block_cost"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			},
			{
				"power_vs_chaos",
				"push_block_arc"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"attack_speed"
			},
			{
				"power_vs_chaos",
				"stamina"
			},
			{
				"power_vs_chaos",
				"block_cost"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"push_block_arc"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"attack_speed"
			},
			{
				"deus_coins_greed",
				"stamina"
			},
			{
				"deus_coins_greed",
				"block_cost"
			}
		},
		unique = {
			{
				"crit_boost",
				"push_block_arc"
			},
			{
				"crit_chance",
				"push_block_arc"
			},
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"attack_speed",
				"push_block_arc"
			},
			{
				"attack_speed",
				"crit_boost"
			},
			{
				"attack_speed",
				"crit_chance"
			},
			{
				"stamina",
				"push_block_arc"
			},
			{
				"stamina",
				"crit_boost"
			},
			{
				"stamina",
				"crit_chance"
			},
			{
				"stamina",
				"attack_speed"
			},
			{
				"block_cost",
				"push_block_arc"
			},
			{
				"block_cost",
				"crit_boost"
			},
			{
				"block_cost",
				"crit_chance"
			},
			{
				"block_cost",
				"attack_speed"
			},
			{
				"block_cost",
				"stamina"
			},
			{
				"power_vs_skaven",
				"push_block_arc"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"attack_speed"
			},
			{
				"power_vs_skaven",
				"stamina"
			},
			{
				"power_vs_skaven",
				"block_cost"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			},
			{
				"power_vs_chaos",
				"push_block_arc"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"attack_speed"
			},
			{
				"power_vs_chaos",
				"stamina"
			},
			{
				"power_vs_chaos",
				"block_cost"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"push_block_arc"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"attack_speed"
			},
			{
				"deus_coins_greed",
				"stamina"
			},
			{
				"deus_coins_greed",
				"block_cost"
			}
		}
	},
	deus_ranged = {
		common = {
			{
				"crit_boost"
			},
			{
				"crit_chance"
			},
			{
				"power_vs_unarmoured"
			},
			{
				"power_vs_armoured"
			},
			{
				"power_vs_large"
			},
			{
				"power_vs_frenzy"
			},
			{
				"power_vs_skaven"
			},
			{
				"power_vs_chaos"
			},
			{
				"deus_coins_greed"
			}
		},
		rare = {
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"crit_boost"
			},
			{
				"power_vs_armoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"crit_boost"
			},
			{
				"power_vs_large",
				"crit_chance"
			},
			{
				"power_vs_large",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"crit_boost"
			},
			{
				"power_vs_frenzy",
				"crit_chance"
			},
			{
				"power_vs_frenzy",
				"power_vs_unarmoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"power_vs_unarmoured"
			},
			{
				"power_vs_skaven",
				"power_vs_armoured"
			},
			{
				"power_vs_skaven",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"power_vs_frenzy"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"power_vs_unarmoured"
			},
			{
				"power_vs_chaos",
				"power_vs_armoured"
			},
			{
				"power_vs_chaos",
				"power_vs_large"
			},
			{
				"power_vs_chaos",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"power_vs_unarmoured"
			},
			{
				"deus_coins_greed",
				"power_vs_armoured"
			},
			{
				"deus_coins_greed",
				"power_vs_large"
			},
			{
				"deus_coins_greed",
				"power_vs_frenzy"
			}
		},
		exotic = {
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"crit_boost"
			},
			{
				"power_vs_armoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"crit_boost"
			},
			{
				"power_vs_large",
				"crit_chance"
			},
			{
				"power_vs_large",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"crit_boost"
			},
			{
				"power_vs_frenzy",
				"crit_chance"
			},
			{
				"power_vs_frenzy",
				"power_vs_unarmoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"power_vs_unarmoured"
			},
			{
				"power_vs_skaven",
				"power_vs_armoured"
			},
			{
				"power_vs_skaven",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"power_vs_frenzy"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"power_vs_unarmoured"
			},
			{
				"power_vs_chaos",
				"power_vs_armoured"
			},
			{
				"power_vs_chaos",
				"power_vs_large"
			},
			{
				"power_vs_chaos",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"power_vs_unarmoured"
			},
			{
				"deus_coins_greed",
				"power_vs_armoured"
			},
			{
				"deus_coins_greed",
				"power_vs_large"
			},
			{
				"deus_coins_greed",
				"power_vs_frenzy"
			}
		},
		unique = {
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"crit_boost"
			},
			{
				"power_vs_armoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"crit_boost"
			},
			{
				"power_vs_large",
				"crit_chance"
			},
			{
				"power_vs_large",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"crit_boost"
			},
			{
				"power_vs_frenzy",
				"crit_chance"
			},
			{
				"power_vs_frenzy",
				"power_vs_unarmoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"power_vs_unarmoured"
			},
			{
				"power_vs_skaven",
				"power_vs_armoured"
			},
			{
				"power_vs_skaven",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"power_vs_frenzy"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"power_vs_unarmoured"
			},
			{
				"power_vs_chaos",
				"power_vs_armoured"
			},
			{
				"power_vs_chaos",
				"power_vs_large"
			},
			{
				"power_vs_chaos",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"power_vs_unarmoured"
			},
			{
				"deus_coins_greed",
				"power_vs_armoured"
			},
			{
				"deus_coins_greed",
				"power_vs_large"
			},
			{
				"deus_coins_greed",
				"power_vs_frenzy"
			}
		}
	},
	deus_ranged_ammo = {
		common = {
			{
				"crit_boost"
			},
			{
				"crit_chance"
			},
			{
				"power_vs_unarmoured"
			},
			{
				"power_vs_armoured"
			},
			{
				"power_vs_large"
			},
			{
				"power_vs_frenzy"
			},
			{
				"power_vs_skaven"
			},
			{
				"power_vs_chaos"
			},
			{
				"deus_coins_greed"
			}
		},
		rare = {
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"crit_boost"
			},
			{
				"power_vs_armoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"crit_boost"
			},
			{
				"power_vs_large",
				"crit_chance"
			},
			{
				"power_vs_large",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"crit_boost"
			},
			{
				"power_vs_frenzy",
				"crit_chance"
			},
			{
				"power_vs_frenzy",
				"power_vs_unarmoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"power_vs_unarmoured"
			},
			{
				"power_vs_skaven",
				"power_vs_armoured"
			},
			{
				"power_vs_skaven",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"power_vs_unarmoured"
			},
			{
				"power_vs_chaos",
				"power_vs_armoured"
			},
			{
				"power_vs_chaos",
				"power_vs_large"
			},
			{
				"power_vs_chaos",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"power_vs_unarmoured"
			},
			{
				"deus_coins_greed",
				"power_vs_armoured"
			},
			{
				"deus_coins_greed",
				"power_vs_large"
			},
			{
				"deus_coins_greed",
				"power_vs_frenzy"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			}
		},
		exotic = {
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"crit_boost"
			},
			{
				"power_vs_armoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"crit_boost"
			},
			{
				"power_vs_large",
				"crit_chance"
			},
			{
				"power_vs_large",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"crit_boost"
			},
			{
				"power_vs_frenzy",
				"crit_chance"
			},
			{
				"power_vs_frenzy",
				"power_vs_unarmoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"power_vs_unarmoured"
			},
			{
				"power_vs_skaven",
				"power_vs_armoured"
			},
			{
				"power_vs_skaven",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"power_vs_unarmoured"
			},
			{
				"power_vs_chaos",
				"power_vs_armoured"
			},
			{
				"power_vs_chaos",
				"power_vs_large"
			},
			{
				"power_vs_chaos",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"power_vs_unarmoured"
			},
			{
				"deus_coins_greed",
				"power_vs_armoured"
			},
			{
				"deus_coins_greed",
				"power_vs_large"
			},
			{
				"deus_coins_greed",
				"power_vs_frenzy"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			}
		},
		unique = {
			{
				"crit_chance",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_boost"
			},
			{
				"power_vs_unarmoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"crit_boost"
			},
			{
				"power_vs_armoured",
				"crit_chance"
			},
			{
				"power_vs_armoured",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"crit_boost"
			},
			{
				"power_vs_large",
				"crit_chance"
			},
			{
				"power_vs_large",
				"power_vs_unarmoured"
			},
			{
				"power_vs_large",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"crit_boost"
			},
			{
				"power_vs_frenzy",
				"crit_chance"
			},
			{
				"power_vs_frenzy",
				"power_vs_unarmoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_armoured"
			},
			{
				"power_vs_frenzy",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"crit_boost"
			},
			{
				"power_vs_skaven",
				"crit_chance"
			},
			{
				"power_vs_skaven",
				"power_vs_unarmoured"
			},
			{
				"power_vs_skaven",
				"power_vs_armoured"
			},
			{
				"power_vs_skaven",
				"power_vs_large"
			},
			{
				"power_vs_skaven",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"crit_boost"
			},
			{
				"power_vs_chaos",
				"crit_chance"
			},
			{
				"power_vs_chaos",
				"power_vs_unarmoured"
			},
			{
				"power_vs_chaos",
				"power_vs_armoured"
			},
			{
				"power_vs_chaos",
				"power_vs_large"
			},
			{
				"power_vs_chaos",
				"power_vs_frenzy"
			},
			{
				"power_vs_chaos",
				"deus_coins_greed"
			},
			{
				"deus_coins_greed",
				"crit_boost"
			},
			{
				"deus_coins_greed",
				"crit_chance"
			},
			{
				"deus_coins_greed",
				"power_vs_unarmoured"
			},
			{
				"deus_coins_greed",
				"power_vs_armoured"
			},
			{
				"deus_coins_greed",
				"power_vs_large"
			},
			{
				"deus_coins_greed",
				"power_vs_frenzy"
			},
			{
				"power_vs_skaven",
				"deus_coins_greed"
			}
		}
	}
}

for iter_0_2, iter_0_3 in pairs(var_0_0.buff_templates) do
	local var_0_2 = iter_0_3.buffs

	fassert(#var_0_2 == 1, "property buff has more than one sub buff, add multiple buffs from the property instead")

	var_0_2[1].name = iter_0_2
end

BuffUtils.apply_buff_tweak_data(var_0_0.buff_templates, var_0_1)

for iter_0_4, iter_0_5 in pairs(var_0_0.buff_templates) do
	fassert(not WeaponProperties.buff_templates[iter_0_4], "duplicate buff_template found between WeaponProperties.buff_templates and buff_templates added by morris dlc")

	WeaponProperties.buff_templates[iter_0_4] = iter_0_5
end

for iter_0_6, iter_0_7 in pairs(var_0_0.properties) do
	fassert(not WeaponProperties.properties[iter_0_6], "duplicate properties found between WeaponProperties.properties and properties added by morris dlc")

	WeaponProperties.properties[iter_0_6] = iter_0_7
end

for iter_0_8, iter_0_9 in pairs(var_0_0.combinations) do
	fassert(not WeaponProperties.combinations[iter_0_8], "duplicate combinations found between WeaponProperties.combinations and combinations added by morris dlc")

	WeaponProperties.combinations[iter_0_8] = iter_0_9
end
